### ISSUE TITLE
Ng-repeat error because of dupes.

### ISSUE THREAD

**Issue by adalberth** [agrublev/angularLocalStorage#54] opened 2014-08-08 09:33 UTC
Fix: change "var saver = $window.json.." to:
var saver = $window.JSON.stringify(value, function (key, val) {
    if (key == '$$hashKey') {
        return undefined;
    }
    return val;
});

**Comment by hppycoder** [comment] 2015-01-28 00:10
Closing as duplicate of #41 

Thank you for finding the same thing, will get this into a PR shortly. Once a simple sample has been setup and it can be tested!

**Closed by hppycoder** 2015-01-28 00:10 UTC
